# Generated by Django 5.0.6 on 2024-07-02 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=200, null=True, verbose_name='place')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='timestamp')),
                ('action', models.CharField(blank=True, choices=[('walk', 'walk outside'), ('drink', 'drink more water'), ('good_mood', 'be friendly')], max_length=200, null=True, verbose_name='action')),
                ('is_nice', models.BooleanField(default=False, verbose_name='nice habit')),
                ('period', models.CharField(blank=True, choices=[('daily', 'daily'), ('weekly', 'weekly')], max_length=50, null=True, verbose_name='period')),
                ('lead_time', models.IntegerField(blank=True, null=True, verbose_name='time to lead')),
                ('reward', models.CharField(blank=True, max_length=100, null=True, verbose_name='reward')),
                ('is_public', models.BooleanField(default=False, verbose_name='publish')),
                ('habits', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='related habis')),
            ],
            options={
                'verbose_name': 'habit',
                'verbose_name_plural': 'habits',
            },
        ),
    ]
